### ISSUE TITLE
Your packages have been downloaded NaN times last month.

### ISSUE THREAD

**Issue by Qix-** [yamadapc/am-i-used#1]
<img width="348" alt="screen shot 2015-08-23 at 4 24 29 pm" src="https://cloud.githubusercontent.com/assets/885648/9430449/75b71d54-49b3-11e5-9ddc-80a584a0705d.png">

Definitely not intended :)

**Comment by Qix-** [comment]
It's more than likely due to one of the packages being too new, and it displays `undefined` as the count in the list.

**Comment by dasilvacontin** [comment]
+1 :+1:

**Comment by yamadapc** [comment]
Thanks, @dasilvacontin had some `undefined` `.downloads` fields :)
Super helpful comment had missed it. `0.0.6` closes.

**Comment by Qix-** [comment]
No problem, thanks ^_^

**Comment by dasilvacontin** [comment]
Happy to serve as guinea pig. ;)
