### ISSUE TITLE
Format the total counts with commas

### ISSUE THREAD

**Issue by Qix-** [yamadapc/am-i-used#3]
Would it be possible to format the counts with commas? i.e. `3123888` -> `3,123,888`

**Comment by yamadapc** [comment]
It's possible, but I'll not do it. Here's my suggestion if you want this:

```
am-i-used tjholowaychuk | grep ' - ' | awk '{print $3}' | xargs printf "%'d\n"
```

Which is a good show of awesomeness with UNIX.
